### ISSUE TITLE
[Suggestion] Allow registration of 'docs' for completions

### ISSUE THREAD

**Issue by ryantheleach** [Mojang/brigadier#108]
Example from worldedit, which has managed to add flags into the completion engine.

![image](https://user-images.githubusercontent.com/141554/147569665-e2e33769-04c5-43b5-811f-b485a27b9b07.png)

When completions are difficult to understand, or a reminder is needed on what a specific completion does, it would be handy for the client to be able to get some registered help text associated with an argument position.

e.g. additional text could be displayed for either the selected argument in game, or all the arguments in the list.

**Comment by emilyy-dev** [comment]
This is already possible with the `Message tooltip` argument in [`SuggestionsBuilder::suggest`](https://github.com/Mojang/brigadier/blob/cf754c4ef654160dca946889c11941634c5db3d5/src/main/java/com/mojang/brigadier/suggestion/SuggestionsBuilder.java#L66).

As far as Minecraft is concerned, the client makes the completion suggestion hoverable displaying the tooltip.

![image](https://user-images.githubusercontent.com/35617540/147596571-ff2fdcb7-b0fc-4efd-b4c7-fde3bd6a25e8.png)
