### ISSUE TITLE
Why do I have to use CommandDispatcher<Object> and not CommandDispatcher<CommandSender>?

### ISSUE THREAD

**Issue by ajh123** [Mojang/brigadier#111]
Ok, so I've created a CommandDispatcher like
```java
private final CommandDispatcher<Object> dispatcher = new CommandDispatcher<>();
```

I have and abstract class called CommandSender, (I've also tried it as an interface)
```java
public abstract class CommandSender {
	public abstract void sendMessage(JSONTextComponent message);
}
```
I have various classes that extend the CommandSender.

For example I have to create a command like this
```java
	private void helpCommand(CommandContext<Object> c) {
		CommandContext<CommandSender> context = (CommandContext<CommandSender>) (CommandContext<? extends Object>) c;
		CommandSender sender = context.getSource();
		...
	}

	private void start() {
		this.dispatcher.register(literal("help")
		.then(
			argument("page", integer())
			.executes(c -> {
				helpCommand(c);
				return 1;
			})
		)
		.then(
			argument("comm", string())
			.executes(c -> {
				helpCommand(c);
				return 1;
			})
		)
		.executes(c -> {
			helpCommand(c);
			return 1;
		}));
	...
``` 

If my helpCommand function and dispatcher was like this
```java
	private final CommandDispatcher<CommandSender> dispatcher = new CommandDispatcher<>();

	private void helpCommand(CommandContext<CommandSender> c) {
		CommandSender sender = context.getSource();
		...
	} 
```
I get an error at where the helpCommand is called because 'c' is a ```CommandContext<Object>``` not ```CommandContext<CommandSender>```.
Is there a way to make 'c' a ```CommandContext<CommandSender>``` without my dispatcher needing to be a ```CommandDispatcher<Object>``` and casting in the helpCommand.

**Comment by Placeblock** [comment]
I think i have the same problem.
The problem is, that if i use the static literal() or argument() functions java doesn't know that the source of my sub-node passed to literal() or argument() has to have the same type as the container node.

I simplified the problem a bit:

`java
    public static void main(String[] args) {
        Literal<String> literal = Literal.<String>literal()
            .then(
                Literal.literal().getThis()
            );
    }

    @Getter
    private static abstract class Argument<S, T extends Argument<S, T>> {
        private final List<Argument<S, ?>> children = new ArrayList<>();

        public abstract T getThis();

        public T then(Argument<S, ?> argument) {
            this.children.add(argument);
            return this.getThis();
        }
    }

    private static class Literal<S> extends Argument<S, Literal<S>> {

        @Override
        public Literal<S> getThis() {
            return this;
        }

        public static <S> Literal<S> literal() {
            return new Literal<>();
        }
    }
`
For my simple test i made getThis() public, and if i execute it without getThis() in line 4 everything just works as intended, but as soon as i use getThis(), etc. it throws an error.

Can somebody explain this to me? I read some articles about Type Inference and as far as i understood them everything should just work fine... or is there something wrong with my code?

**Comment by ajh123** [comment]
Sounds like a similar issue.

**Comment by limwa** [comment]
The correct solution for @ajh123's problem, I think, would be changing the helpCommand arguments from `CommandContext<Object> c` to `CommandContext<CommandSender> c` or `CommandContext<? extends Object> c` (the later is if you want to receive both Object or CommandSender in the same method.

Of course, another solution that could work would be to overload the method, thats is creating one method for `CommandContext<Object>` and another one for `CommandContext<CommandSender>`, but I don't really know if it even compiles.

**Comment by limwa** [comment]
If you know that your source for commands will **always** be a CommandSender, though, I highly recommend changing your CommandDispatcher type from `CommandDispatcher<Object>` to `CommandDispatcher<CommandSender>`

**Comment by Placeblock** [comment]
You can simplify the problem further with this simple Node class:

```java
public class Node<S> {
    public Node<S> addChild(Node<S> node) {
        return this;
    }
}
```

If you try to create a simple Tree structure with this:
```java
new Node<String>().addChild(
    new Node<>().addChild(
        new Node<>()
    )
)
```
It throws an error. It seems like the generic type S gets lost after instantiating a new Node and doesn't get passed to the childnode because of type erasure. Has somebody a solution for this?

**Comment by limwa** [comment]
Can you provide the error that you are getting?

**Comment by Placeblock** [comment]
`error: incompatible types: Node<Object> cannot be converted to Node<String>` when trying to compile

**Comment by limwa** [comment]
That is a limitation with the Java compiler, as you stated. The way Brigadier overcomes this is by adding a method that does the same thing, but with the correct generic type information 

https://github.com/Mojang/brigadier/blob/master/src/main/java/com/mojang/brigadier/builder/LiteralArgumentBuilder.java#L16-L18

**Comment by Placeblock** [comment]
```java
public class Main {

    public static void main(String[] args) {
        Node.<String>node().addChild(
            Node.node().addChild(
                Node.node()
            )
        );
    }

    private static class Node<S> {
        public static <S> Node<S> node() {
            return new Node<>();
        }

        public Node<S> addChild(Node<S> node) {
            return this;
        }
    }
}

```

Even if i create a static method it doesn't work...

**Comment by ajh123** [comment]
Even if I use a ```CommandDispatcher<CommandSender>``` I can't register the commands
```java
public class Game {
	private final CommandDispatcher<CommandSender> dispatcher = new CommandDispatcher<>();

	private void helpCommand(CommandContext<CommandSender> context) {
		CommandSender sender = context.getSource();
        }

        private void start() {
		this.dispatcher.register(literal("help")
		.then(
			argument("page", integer())
			.executes(c -> {
				helpCommand(c);
				return 1;
			})
		)
		.then(
			argument("comm", string())
			.executes(c -> {
				helpCommand(c);
				return 1;
			})
		)
		.executes(c -> { // I get an error of error: incompatible types: LiteralArgumentBuilder<Object> cannot be converted to LiteralArgumentBuilder<CommandSender>
		.executes(c -> {
			helpCommand(c);
			return 1;
		}));
        }

        public static void main(String[] args) throws Exception {
		new Game().start();
	}
```

**Comment by ajh123** [comment]
And Java 16 is set in the build.gradle
```gradle
targetCompatibility = 16
sourceCompatibility = 16
```
However my Gradle JVM is set to Java 16 also

**Comment by Placeblock** [comment]
Yea you have the problem i described above, i just wonder why i works for all the other developers using brigadier + i have not found a fix for it. I just changed my java version to 8, but it doesn't work too.

**Comment by ajh123** [comment]
Happy to know it's not just me.

**Comment by portlek** [comment]
you have to specify generic types on static methods which have generic types.
```java
CommandDispatcher<CommandSender> dispatcher = new CommandDispatcher<>();

interface CommandSender {

}

private void helpCommand(CommandContext<CommandSender> context) {
  CommandSender sender = context.getSource();
}

private void start() {
  this.dispatcher.register(LiteralArgumentBuilder.<CommandSender>literal("help")
    .then(
      RequiredArgumentBuilder.<CommandSender, Integer>argument("page", IntegerArgumentType.integer())
        .executes(c -> {
          this.helpCommand(c);
          return 1;
        })
    )
    .then(
      RequiredArgumentBuilder.<CommandSender, String>argument("comm", StringArgumentType.string())
        .executes(c -> {
          this.helpCommand(c);
          return 1;
        })
    )
    .executes(c -> {
      this.helpCommand(c);
      return 1;
    }));
}
```

**Comment by ajh123** [comment]
Thank you! This helps. Could you please document it somewhere?
