### ISSUE TITLE
Redirected commands with arguments act as the command is valid even when it isn't

### ISSUE THREAD

**Issue by Awakened-Redstone** [Mojang/brigadier#133]
The images are after executing the command shown, Minecraft was used as an example
`w` is a redirect of `msg`, `msg` is the original command

![image](https://github.com/Mojang/brigadier/assets/40528665/e1723648-f293-469a-8827-327c2ea68891)
![image](https://github.com/Mojang/brigadier/assets/40528665/f95f52fa-b0e3-481a-9926-b0f698064781)

**Comment by M4ximumPizza** [comment]
Do you know what MC version this is broken on? Looks like a server side issue.

**Comment by Awakened-Redstone** [comment]
I hae tested it on 1.19.4 and 1.19.3

**Comment by Awakened-Redstone** [comment]
Oh, interesting, failed to reproduce on 1.20-pre6
