### ISSUE TITLE
My Bedrock edition of minecraft has Cherry Blossom Capes, and because I voted, I wonder if the java edition will have cherry blossom Capes. My java id and Bedrock id are different. So I'm afraid I won't get the cape for my java version of the game, and I'll be sad.....

### ISSUE THREAD

**Issue by jiahe666666** [Mojang/brigadier#141]
My Bedrock edition of minecraft has Cherry Blossom Capes, and because I voted, I wonder if the java edition will have cherry blossom Capes. My java id and Bedrock id are different. So I'm afraid I won't get the cape for my java version of the game, and I'll be sad.....

**Comment by M4ximumPizza** [comment]
Ummm, so this is repo is for one of the librarys called brigadier. If you have a bug report, you can report it here. Or any concerns you can go to the MC bug reports https://bugs.mojang.com/secure/Dashboard.jspa

**Comment by MiniDigger** [comment]
and for this particular issue, since its not a bug in the game, you are best off contacting support: https://help.minecraft.net/hc/en-us/request/new?ticket_form_id=360001225811
