### ISSUE TITLE
[question]: how override vanilla command.

### ISSUE THREAD

**Issue by MairwunNx** [Mojang/brigadier#58]
## Is it possible to override minecraft vanilla commands? I just try register command with same arguments and name, but, it work incorrect.

**Comment by PixelLima** [comment]
This is not the repository for that. This is for the command dispatcher, called Brigadier. This means that this repository has no connection to Minecraft itself, even if Brigadier is used in Minecraft. If you are using Bukkit, Spigot, Paper, Paperspigot, ForgeServer, etc., please go to their respective support pages and report your issue there.

**Comment by MairwunNx** [comment]
@PixelLima Yes, sorry, it can be marked as `invalid`. I want to override them on the `Forge API` platform. 

## Issue closed.
