### ISSUE TITLE
Command with argument player and then argument int not working correctly.

### ISSUE THREAD

**Issue by MairwunNx** [Mojang/brigadier#59]
![image](https://user-images.githubusercontent.com/39625750/67634855-db250300-f8d1-11e9-871b-5442bd155eb9.png)

First message on screenshot i get when type `/test MairwunNx`
Second message on screenshot i get when type "/test MairwunNx 15"

![image](https://user-images.githubusercontent.com/39625750/67634870-0d366500-f8d2-11e9-8cd2-c345cc01b30b.png)

**Comment by PixelLima** [comment]
Your Brigadier command structure is completely wrong. That is why it is not working.

**Comment by MairwunNx** [comment]
@PixelLima How should she look right?

**Comment by PixelLima** [comment]
```Java
Commands.argument("player", EntityArgument.player())
.then(
    Commands.argument("duration", IntegerArgumentType(1, 120))
    .executes(it -> execute(it, IntegerArgumentType.getInteger("duration")))
).executes(it -> execute(it, config.defaultDuration))

**Comment by PixelLima** [comment]
Of course, that goes inside the first then()

**Comment by MairwunNx** [comment]
@PixelLima Thank you for writing the correct code, it works. 🎉

## Happy hacking 🍀!
