### ISSUE TITLE
Repository not updated to 1.0.500

### ISSUE THREAD

**Issue by Pante** [Mojang/brigadier#60]
Recently brigadier 1.0.500 was pushed to Mojang’s maven repository. However, this repository was last updated almost a year ago and is still on 1.0.17. Are there any plans to update this repository?

**Comment by Pokechu22** [comment]
The `Last-Modified` header on 1.0.500 is `Mon, 02 Jul 2018 09:57:33 GMT` while 1.0.17 is `Tue, 19 Feb 2019 12:42:39 GMT`.  Also, doing a diff between the source jars [for 1.0.500](https://libraries.minecraft.net/com/mojang/brigadier/1.0.500/brigadier-1.0.500-sources.jar) and [for 1.0.17](https://libraries.minecraft.net/com/mojang/brigadier/1.0.17/brigadier-1.0.17-sources.jar) makes it appear that 1.0.500 is missing a lot of things (license headers from 872658c7372b47a2938f7a836cd33deebf8feb9a, some comments from 8e9859e4712f06ad287f8c0a18725309151778ec, `LongArgumentType` from #10, among others).  Additionally [1.15-pre2](https://launchermeta.mojang.com/v1/packages/eb31a8c6e71b08568b0b76c96bfe0935ba25367a/1.15-pre2.json) uses 1.0.17.  My guess is that this is just version numbers being weird, and not the repository being out of date with something else, but an official statement would be nice.

**Comment by Pante** [comment]
Ah I see, I only got a notification from dependabot about it so I didn’t really check the last modified date, my bad.
