### ISSUE TITLE
我的世界加油！

### ISSUE THREAD

**Issue by Ryanyuanao** [Mojang/brigadier#63]
我的世界加油！

**Comment by baohong-cn228813509** [comment]
要是没有minecraft就没有傻逼迷你世界。祝迷你世界快快下架。`<iframe src="//player.bilibili.com/player.html?aid=28262679&bvid=BV1vs411w7qG&cid=48861966&page=1" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true"> </iframe>`

**Comment by baohong-cn228813509** [comment]
为什么嵌入代码显示不出来艹。https://www.bilibili.com/video/BV1vs411w7qG/

**Comment by sjx233** [comment]
Have you read the [GitHub Community Guidelines](https://help.github.com/cn/github/site-policy/github-community-guidelines)?

**Comment by CarierxGroup** [comment]
This is a formal place for submitting issues, if you want to cheer, please leave here.

**Comment by MCUmbrella** [comment]
Thanks for supporting Minecraft but the 'issues' page is a place for people who asking for help or has suggestions and not for express your emotions. The better places to do this are the offical discord server, Minecraft forum and so on, not here.
