### ISSUE TITLE
[not related to brigadier but i couldnt find any other place to ask u guys :(  ] Can you guys make the minecraft's world generation open source? THAT WOULD BE AWESOME FOR SPEEDRUNNERS

### ISSUE THREAD

**Issue by satyamedh** [Mojang/brigadier#72]
heyy! Just think how better speedruns could be if the generation code was public
i mean I could just decompile but it would be simple if they made it open souce right????

thx!
also can you tell your parent comany to:
RESTORE https://www.github.com/Microsoft/malmo

it is SOOOOOOO usefull ;)

**Comment by sjx233** [comment]
Asking Mojang to open-source this code is almost impossible for now. Decompilation has already been made simple by [some](https://github.com/hube12/DecompilerMC) [tools](https://github.com/MaxPixelStudios/MinecraftDecompiler), and you may give them a try.

**Comment by satyamedh** [comment]
yea I know(i already did it) I don't understand why they can't do it?

just think how easy and quick speedruns could be

**Comment by XjCyan1de** [comment]
please close issue

**Comment by XjCyan1de** [comment]
@satyamedh use https://github.com/FabricMC/yarn

**Comment by satyamedh** [comment]
I used it

**Comment by XjCyan1de** [comment]
@satyamedh please close issue

**Comment by satyamedh** [comment]
I won't till an official response is posted by Mojang

**Comment by lukeeey** [comment]
They don’t really reply here anymore

**Comment by darius-leong** [comment]
I mean, if other programmers wanted to figure out minecraft's generation algorithm, it could be made open source.
That would be quite interesting. I don't know where you are getting the idea that it would be good for speedrunners.

**Comment by kotx** [comment]
This has NOTHING to do with brigadier. Please close this issue.

**Comment by Chew** [comment]
![image](https://user-images.githubusercontent.com/8278263/88579973-8c4afc00-d010-11ea-81b6-ce4b455fac27.png)

You're in the wrong spot bucko

**Comment by satyamedh** [comment]
@Chew idk any other place to tell them xD @kotx ok :( @darius-leong ye exactly @lukeeey :( :(
i'm closing this now, if u wanna help me get into it and get how it works pls contact me in discord: ||satyamedh||#9549

**Comment by Chew** [comment]
I mean I totally agree but this just isn't the place to ask :( maybe try asking on twitter or something?

**Comment by satyamedh** [comment]
@Chew haha if I can have a twitter. I'm sure 15yr olds cant

**Comment by kotx** [comment]
> haha if I can have a twitter. I'm sure 15yr olds cant

Twitter's age requirement is 13.

**Comment by Chew** [comment]
Oh hi kot uwu

**Comment by kotx** [comment]
> Oh hi kot uwu

👋
