### ISSUE TITLE
Giving other Java applications the ability to play in Minecraft.

### ISSUE THREAD

**Issue by phoebe-leong** [Mojang/brigadier#73]

**Comment by PixelLima** [comment]
What is this even supposed to mean?

**Comment by darius-leong** [comment]
Ok. Let me provide a description:

So, I'm making a java application that opens minecraft and records seeds by making new worlds. But it can't press buttons or anything, it needs access to the code.

**Comment by Pokechu22** [comment]
I don't think Brigadier is relevant to that; Brigadier is only the command-parsing library.  You probably want to use something like [java.awt.Robot](https://docs.oracle.com/javase/8/docs/api/java/awt/Robot.html), but this isn't the right place to discuss it.

**Comment by darius-leong** [comment]
Thanks.

**Comment by PixelLima** [comment]
Please close this issue.
