### ISSUE TITLE
A String containing less / greater than signs aren't treated as Strings 

### ISSUE THREAD

**Issue by l1ving** [Mojang/brigadier#78]
Title. `563138570953687061` is valid as a String, while `<@563138570953687061>` is not. `56313857095368706<1` also is not a "String" according to Brigadier. If this is intentional it would be nice to work around it

**Comment by vdvman1** [comment]
Are you referring to unquoted strings? Strings with quotes around them most certainly allow those characters, unquoted strings only allow certain characters.
There are two methods for reading a string, [unquoted strings](https://github.com/Mojang/brigadier/blob/559d8f39727e98d374b0726ad88aed9832beee4e/src/main/java/com/mojang/brigadier/StringReader.java#L177) and [quoted strings](https://github.com/Mojang/brigadier/blob/559d8f39727e98d374b0726ad88aed9832beee4e/src/main/java/com/mojang/brigadier/StringReader.java#L185)

**Comment by vdvman1** [comment]
When you call [readString](https://github.com/Mojang/brigadier/blob/559d8f39727e98d374b0726ad88aed9832beee4e/src/main/java/com/mojang/brigadier/StringReader.java#L222) it first checks if it starts with a `"`, and if it does it reads it as a quoted string, otherwise reads it as an unquoted string

**Comment by l1ving** [comment]
https://github.com/kami-blue/bot-kt/blob/3e87d3b1a6bb7745f3b663f9d13466a2a46619c1/src/main/kotlin/BrigadierDsl.kt#L97

I'm assuming StringArgumentType.string() is the same readString you're referring to. 

My input is unquoted, yes. It would be pretty annoying to have to quote that

**Comment by vdvman1** [comment]
`StringArgumentType.string()` accepts either quoted or unquoted as it calls `readString()`
Most special characters are not allowed in unquoted strings, the user of the command just needs to use quotes if they want special characters, this is normal for commands

**Comment by l1ving** [comment]
Is there any way I could get around this? Such as adding an exception in Brigadier's code?

**Comment by l1ving** [comment]
For context, a ping on Discord looks like `<@Long>` to a bot, and I'd like it treated as a single String so I don't have to split a greedy string, which is quite annoying to do

**Comment by PixelLima** [comment]
Brigadier is made so that you can add your own argument types. Therefore, I personally think it would be best if you implemented your own argument type.

**Comment by l1ving** [comment]
Do you have documentation on how to do that?

**Comment by vdvman1** [comment]
Brigadier isn't documented, but you can look at the built-in [argument types](https://github.com/Mojang/brigadier/tree/master/src/main/java/com/mojang/brigadier/arguments)

**Comment by l1ving** [comment]
Thank you, ended up using my own argument type. https://github.com/kami-blue/bot-kt/blob/11d2fff/src/main/kotlin/helpers/DiscordUserArgumentType.kt
