### ISSUE TITLE
How??

### ISSUE THREAD

**Issue by KiwiFruit555** [Mojang/brigadier#79]
Ok first: How do I use this?!
second: Could I use this with 1.7 or 1.8?
third: i prolly have more questions

**Comment by MiniDigger** [comment]
since answer to the second question is "hahahahha no", I would assume the others are irrelevant.

**Comment by vdvman1** [comment]
Brigadier is the library that is used for commands in minecraft in 1.13 or later, it is not something that can easily be added to an older version of minecraft

**Comment by KiwiFruit555** [comment]
### OOF

**Comment by MajsterTynek** [comment]
but could be it imported for modders usage?

**Comment by Pokechu22** [comment]
You theoretically could (though you would not have access to the improved command completion functionality, only command dispatch), but you'd be better off updating to a modern version instead of trying to make things work with one that's half a decade old.

**Comment by KiwiFruit555** [comment]
Lol aight
I prolly would not be able to do this anyways :P I don't really know Java
But I don't have enough money for a new computer to upgrade to a newer version. And ik its free to play when u buy an account and you can play any version but on my pc. hahahaha no. anything above 1.14: 10 fps
I don't have a very good pc. 
But sometimes I can get 100 fps on 1.8.9
that is why I like 1.8.9
PVP and fps
Anyways, the only thing I like about 1.16 is foxes. I LOVE FOXES!! but to me, foxes vs fps? I think I know what to choose lol. Sorry foxes
Maybe I will get a new PC for christmas from someone. Who knows? Prolly not tho. The chances of that are slimmer than an electron. It is sad 😔. I can always save
sorry I was rambling lol

thx for the help ig

**Comment by enderger** [comment]
Have you tried [Optifine](https://optifine.net) or the fabric mods [Lithium](https://www.curseforge.com/minecraft/mc-mods/lithium), [Sodium](https://www.curseforge.com/minecraft/mc-mods/sodium), [Phosphor](https://www.curseforge.com/minecraft/mc-mods/phosphor), and/or the optimizations contained within the [Carpet Mod](https://www.curseforge.com/minecraft/mc-mods/carpet)? They all really help make the newer versions run smoothly!
