### ISSUE TITLE
Any document or guide, on how to run it along minecraft ?

### ISSUE THREAD

**Issue by Capconve** [Mojang/brigadier#80]
Wanted to know if there is any detailed document to help newcomers like me on how to run it along with minecraft.

Thanks.

**Comment by vdvman1** [comment]
Minecraft already includes brigadier since 1.13, it is how all the commands in the game are parsed and run.
I am not sure what you mean by "along with minecraft" in this case, brigadier is not a self-contained app, it is the library minecraft uses for all the commands inside the game
